### ISSUE TITLE
Regarding project name

### ISSUE THREAD

**Issue by YoungHoonJun** [EMDC-OS/mg-lru#2]
Does "mglru" stand for Multi-Gen LRU implemented in the Linux kernel? I’m a bit confused about the relationship between the current project features and multi-gen LRU. Are the current project features only applicable to the traditional LRU, or can they also be applied to the newly developed mglru?

**Comment by J-S-Kim** [comment]
Thank you for letting me know. 

Due to changes in the research plan, MGLRU has been excluded from the scope of application. Therefore, it seems inappropriate to have MGLRU in the project name. 

However, since I currently don't have the necessary permissions, I am unable to change the repository name. I will change it once I receive the appropriate permissions.
